# Site Settings
title: Anthony | anthonyawuley.github.io
email: anthony@awuley.com
description: Some text about your blog.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://anthonyawuley.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Anthony Awuley
user_description: Machine Learning Research Scientist
disqus_username: anthonyawuley

# Social Media
# Remove the item if you don't need it
github_username: anthonyawuley
facebook_username: anthonyawuley
twitter_username: anthonyawuley
instagram_username: anthonyawuley
linkedin_username: anthonyawuley
medium_username: anthonyawuley

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
